# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a26dc3531b820f1dc2761c9a11e9ce85c383de658e5f98657464d9f676f754e475b50264cf6cdf14b3b21b7c250746cb31ad32cd5705251e5c80b2296daf58d

test:
  secret_key_base: b4499893851b2b5b5756cb5f0f837a3f3955b3282e94cfdda85bf830958b67cdd2ac20894ec9db2971575c155156bd0b09fe017f38ac01bbf9763a61c389b35a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
